### ISSUE TITLE
Some console.log() are left in the published code

### ISSUE THREAD

**Issue by floriancargoet** [lukasbach/react-complex-tree#1]
**Describe the bug**
Some console.log() are left in the published code.

https://github.com/lukasbach/react-complex-tree/blob/827deb00c277614eb5b6b083fd37522327d4cbd1/packages/core/src/tree/resolveLiveDescriptor.ts#L16-L19

https://github.com/lukasbach/react-complex-tree/blob/58bcbec7f90c0ee962ce1698e46ea8b04b57714d/packages/docs/src/components/PropTable.js#L4-L8

**Screenshots**
![image](https://user-images.githubusercontent.com/110431/131481305-eed30baa-8344-41ee-95b9-8f852efc8c77.png)

**Comment by lukasbach** [comment]
Hi @floriancargoet!

Thank you so much for your issue requests :) I'm very happy about your feedback and especially that you took the time to look into the code.

I've looked into them and fixed them, the fixes are available in `react-complex-tree@v1.1.1`. Please let me know if you find any issues remaining or anything else that is not working as expected. Feel free to respond in the issues or create new ones.

**Comment by floriancargoet** [comment]
Thanks, I'll try the new version when I can and I'll report back!
