### ISSUE TITLE
Drag and Drop on ControlledTreeEnvironment doesn't work

### ISSUE THREAD

**Issue by chalscc** [lukasbach/react-complex-tree#128]
**Describe the bug**
If in a ControlledTreeEnvironment the drag and drop wont work

**To Reproduce**
https://codesandbox.io/s/ng6mme?file=/src/App.tsx

**Expected behavior**
Expecting item to be dropped, it is possible to drag it.
**Desktop (please complete the following information):**

- OS: W10
- Browser: chrome
- Version latest

**Additional context**

With 
`canDragAndDrop={true}
                canReorderItems={true}
                canDropOnItemWithChildren={true}
                canDropOnItemWithoutChildren={true}`
And no restrictions it is not possible to drop the item, the `canDropAt` seems to work fine but also doesn't allow me to drop the item

**Comment by lukasbach** [comment]
Hello @chalscc. In a ControlledTreeEnvironment, you need to implement the logic for handling drag and drop events yourself. If you want to to use the built-in logic for handling drop events, please use an [uncontrolled environment](https://rct.lukasbach.com/docs/guides/uncontrolled-environment) instead.

**Comment by EliotKhachi** [comment]
Hi, I'm having trouble dragging and droppign items in a ControlledTreeEnvironment as well-- and so is this fellow https://stackoverflow.com/q/73048304/19866314.

My onDrop prop is simple for now as I'm just logging the details-- but I'm finding that the target parameter is not being set properly. It's not set to the item I dropped onto-- in fact, it's seemingly random. 
 ```
onDrop={(items, target) => {
                  console.log("Drop detected:", { items, target });
                  handleDrop(items.map(item => item.index as string), target);
                }}
```

I would appreciate any help.

Thanks,
Eliot
