### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by dmt0** [lukasbach/react-complex-tree#132]
Thanks for a great repo!
Could we please have some form of changelog? I couldn't find either changelog or version.md or history.md or descriptions in the releases themselves.

**Comment by lukasbach** [comment]
Hi! You're right, there should definitely be a changelog. Moving forward, I will document changes for each release at https://rct.lukasbach.com/docs/changelog, starting with the next release which will happen in the following days. Thanks for bringing this up.
