### ISSUE TITLE
Coping items

### ISSUE THREAD

**Issue by JustynaKK** [lukasbach/react-complex-tree#140]
First of all, awesome project!

I wanted to ask if it is possible to copy item with CTRL+c from one group and insert it to another group with CTRL+v? That both groups would have this particular item as a child. Or add an option if node is moved or duplicated while dragging.

**Comment by lukasbach** [comment]
Hi  @JustynaKK, react-complex-tree just manages the render-side of the tree, the tree state is managed outside via props, so changes to the state such as copying needs to be implemented outside of the library, and thus is out of scope for this library. But it is possible to add on your own to your tree.

**Comment by JustynaKK** [comment]
Thank you for the response, I figured out how to add required interactions:)
I also wanted to ask, if you could advise what would be the best way to do following: to have an input above the tree to search through all items of the tree, expand groups in which there is a match, and hide all items there is no match (that there is only filtered state showed). Would be very grateful for any hint.
