### ISSUE TITLE
How to use custom data provider?

### ISSUE THREAD

**Issue by jeevasusej** [lukasbach/react-complex-tree#149]
Hi,

How to use custom data provider?
I don't find any example to use that?
[https://rct.lukasbach.com/docs/guides/custom-data-provider](https://rct.lukasbach.com/docs/guides/custom-data-provider)

**Comment by williammyuan** [comment]
`const customData: TreeDataProvider<any> = {
    getTreeItem: (itemId: TreeItemIndex) => {
      return new Promise<TreeItem<any>>((resolve, reject) => {
        const item: TreeItem<string> = {
          index: 'root',
          hasChildren: true,
          children: ['child1', 'child2'],
          data: 'Root item'
        }
        resolve(item)
      })
    },
    getTreeItems: (itemIds: TreeItemIndex[]) => {
      console.log('itemIds:', itemIds)
      return new Promise((resolve) => {
        const items: TreeItem[] = [{
          index: 'root',
          hasChildren: true,
          children: ['child1', 'child2'],
          data: 'Root item'
        }, {
          index: 'child1',
          children: [],
          data: 'Child item 1'
        }, {
          index: 'child2',
          hasChildren: true,
          children: ['child3'],
          data: 'Child item 2'
        }, {
          index: 'child3',
          children: [],
          data: 'Child item 3'
        }]
        resolve(items)
      })
    }
  }`


<UncontrolledTreeEnvironment
      // dataProvider={new StaticTreeDataProvider(items, (item, data) => ({ ...item, data }))}
      dataProvider={customData}
      getItemTitle={item => item.data}
      viewState={{}}
      onDrop={onDrop}
      canDragAndDrop={true}
      canReorderItems={true}
      canDropOnItemWithChildren={true}
      canDropOnItemWithoutChildren={true}
    >
      <Tree treeId="tree-2" rootItem="root" treeLabel="Tree Example" />
    </UncontrolledTreeEnvironment>

**Comment by lukasbach** [comment]
You need to implement the interface specified in the page you posted, for example like @williammyuan suggested. Alternatively you can use the provided [StaticTreeDataProvider](https://rct.lukasbach.com/docs/api/interfaces/TreeEnvironmentRef/#draganddropcontext).

You can look into the implementation of StaticTreeDataProvider for a more elaborate example: https://github.com/lukasbach/react-complex-tree/blob/main/packages/core/src/uncontrolledEnvironment/StaticTreeDataProvider.ts
