### ISSUE TITLE
DnD doesn't work when other component is rendered using `react-dnd` 

### ISSUE THREAD

**Issue by Nishchit14** [lukasbach/react-complex-tree#152]
**Describe the bug**
The drag and drop functionality is being stopped when any other component is rendered with [react-dnd](https://github.com/react-dnd/react-dnd) implementation

**Expected behavior**
The DnD functionality would be working regardless of other dnd lib usage.

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: chrome
- Version 1.1.11

**Comment by williammyuan** [comment]
https://github.com/react-dnd/react-dnd/issues/3344

**Comment by Nishchit14** [comment]
I removed `react-dnd` :D

**Comment by williammyuan** [comment]
> I removed `react-dnd` :D

good job

**Comment by lukasbach** [comment]
Not sure if there can be done anything on rct side since there already is something open on react-dnd side, but happy you were able to fix this that way 😅 I'll close this for now, please reopen or recreate if someone else has this issue again.

**Comment by vovsemenv** [comment]
have same problem, maybe reopen?

**Comment by genixpro** [comment]
@lukasbach I'm also experiencing this issue. Want to use react-dnd for one part of my app and rct for another, but they are conflicting with each other unfortunately.
