### ISSUE TITLE
Can't drop items on an empty tree

### ISSUE THREAD

**Issue by sweco-sedalh** [lukasbach/react-complex-tree#182]
**Describe the bug**

Can't drop items on an empty tree (without any items).

**To Reproduce**
1. Setup an environment with two `<Tree />`s, one of which is empty
2. Try to drag items from the tree that's not empty to the one that is
3. Item cannot be dropped anywhere

https://codesandbox.io/s/react-complex-tree-playground-forked-96pwzt

**Expected behavior**

Dropping can happen on any part of the tree. Setting `{min-,}{height,width}` can be used to set a size for an empty tree, the entire of which is a valid drop target.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 107.0.5304.107

**Additional context**

**Comment by lukasbach** [comment]
Hi @sweco-sedalh! Thanks for your report. This should now be working as of v2.0.0, please see this storybook as an example: https://rct.lukasbach.com/storybook/?path=/story/core-basic-examples--drop-on-empty-tree

Please note that the drag-over needs to be performed over the tree container component for it to register on empty trees, so the tree container component needs a minimum height for it to work. You can customize this by giving a minimum height to the component rendered with `renderTreeContainer` which receives the `containerProps`.

**Comment by sweco-sedalh** [comment]
Thanks, I can can confirm that this issue is resolved in 2.0.0!
