### ISSUE TITLE
Hide arrow if all children are moved

### ISSUE THREAD

**Issue by ZekiJohn** [lukasbach/react-complex-tree#188]
How can I hide the dropdown arrow if every last one of a child is moved out.

**Comment by Shaglock** [comment]
Whether arrow is  shown or not depends only on `isFolder` (previously `hasChildren`) prop of the node. So you have to change that property for the node when all children are moved out. 

I agree that this is not very intuitive and would be better if it was just checking current state of item and not this `isFolder` property. Maybe this could be done with custom `renderItemArrow` renderer 

Check this discussion
https://github.com/lukasbach/react-complex-tree/pull/70

**Comment by ZekiJohn** [comment]
ok Thanks Shaglock 🙏🏾
