### ISSUE TITLE
Dragging folder into a descendant folder causes both of them to disappear

### ISSUE THREAD

**Issue by MarksCode** [lukasbach/react-complex-tree#227]
Looks like there's a bug if you drop a folder onto a child folder, both of them will disappear.

_Originally posted by @MarksCode in https://github.com/lukasbach/react-complex-tree/issues/219#issuecomment-1444798211_

**Comment by lukasbach** [comment]
Ops, should be fixed as of 2.1.1!

**Comment by JongSikLim** [comment]
I used canDropAt to prevent this bug, and I'm glad to hear it's fixed.
