### ISSUE TITLE
Search icon does not follow search input when scrolling

### ISSUE THREAD

**Issue by khamphou** [lukasbach/react-complex-tree#239]
**Describe the bug**
in page containing a large number of tree nodes, in search mode, and when scrolling down, the search input follows the scroll, but not the search icon.

**To Reproduce**
- test in a short window, so scrollbar appears
- open codesandbox page at https://codesandbox.io/s/react-complex-tree-expandcollapse-all-phbie6
- expand all items
- perform a search using a text : orange
- scroll down, search input follows the windows canvas, not the search icon, which remains at top of the page

the issue is present also in the official document page at https://rct.lukasbach.com/storybook/?path=/docs/core-react-refs--expand-or-collapse-all

**Expected behavior**
search icon and input text are following the windows canvas

**Screenshots**
![image](https://user-images.githubusercontent.com/7923583/226146622-d7a21052-e0eb-4399-8841-ad8c7e48bd68.png)

**Desktop (please complete the following information):**

- OS: Windows
- BrowserEdge
- Version xx

**Additional context**
react-complex-tree 2.1.1

**Comment by lukasbach** [comment]
Hey, thanks for the report! This should be fixed as of 2.1.2.
