### ISSUE TITLE
Unable to collapseall when using ControlledTreeEnvironment

### ISSUE THREAD

**Issue by khamphou** [lukasbach/react-complex-tree#240]
**Describe the bug**
ExpandAll does not work, no sub nodes are expanded
CollapseAll collapse only one parent folder at a time

**To Reproduce**
- visit page https://codesandbox.io/s/react-complex-treeview-controlledtreeenvironment-pw3cly
- click on expandall button => nothing happens
- expand manually many nodes
- click on collapseall, only one node is collapsed at a time

**Expected behavior**
all sub nodes should open, none of them are expanded using the controlledtreeenvironment.
it works fine using uncontrolledtreeenvironment.

**Screenshots**
![image](https://user-images.githubusercontent.com/7923583/226146980-30939df0-92dc-4f9d-86f1-464af2efa98f.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Edge
- Version 2023

**Additional context**
react-complex-tree 2.1.1

**Comment by lukasbach** [comment]
Hi, I just had a look, and there seems to be some issues with closures in your code. Replace the `onExpandItem` and `onCollapseItem` props with

```jsx

      onExpandItem={(item) => {
        console.log("expand", item);
        setExpandedItems((items) => [...items, item?.index]);
      }}
      onCollapseItem={(item) =>
        setExpandedItems((items) =>
          items.filter((expandedItemIndex) => expandedItemIndex !== item?.index)
        )
      }
```

Then it works: https://codesandbox.io/s/react-complex-tree-expandall-closure-fix-ekssib

**Comment by khamphou** [comment]
thank you for your help.
sorry for the response delay. i was sick last weeks.
