### ISSUE TITLE
Example for drag and drog with controlled tree?

### ISSUE THREAD

**Issue by andreash** [lukasbach/react-complex-tree#269]
Lukas - I like your tree - great job!

**Is your feature request related to a problem? Please describe.**
I am trying to implement a controlled tree with drag and drop and was looking for examples.

**Describe the solution you'd like**
An example for drag and drop for controlled trees.

Best,
Andreas

**Comment by lukasbach** [comment]
Maybe not the best example in terms of documentation, but maybe looking at the implementation of UncontrolledTreeEnvironment (https://github.com/lukasbach/react-complex-tree/blob/main/packages/core/src/uncontrolledEnvironment/UncontrolledTreeEnvironment.tsx) might be helpful - it essentially is just a wrapper around a controlled tree that provides pre-defined implementations for all necessary handlers.

**Comment by lukasbach** [comment]
I expanded the [docs on static data providers](https://rct.lukasbach.com/docs/guides/static-data-provider/) and on [custom data providers](https://rct.lukasbach.com/docs/guides/custom-data-provider/), maybe that gives some additional help when implementing dnd with custom data.

**Comment by SyedMisbahUrRehman** [comment]
Dear @lukasbach , can you please provide a minimal reproducible example for demonstration of Controlled tree environemt .
Thansk a lot!

Misbah

**Comment by lukasbach** [comment]
Hi @SyedMisbahUrRehman, the docs on controlled environments have several examples for how to implement them: https://rct.lukasbach.com/docs/guides/controlled-environment
