### ISSUE TITLE
Request for `context.stopRenamingItem(item.index)` as counter for existing startRenamingItem function

### ISSUE THREAD

**Issue by LydiaF** [lukasbach/react-complex-tree#271]
**Is your feature request related to a problem? Please describe.**
I am using a controlled tree and using `<input />` directly to render the item as we want to mimic the Workflowy editing. Calling `context.startRenamingItem(item.index)` on keystroke in the input field, enables the user to use the arrow cursor in the text field. 

The problem is I can't figure out how to **stop** renaming the item programatically. This means we can't get the keyboard arrow shortcuts in action again when user is finished editing.

**Describe the solution you'd like**
On context object, have a function called stopRenamingItem.

**Describe alternatives you've considered**
Can't think of a solution.

**Additional context**

Thanks!

**Comment by lukasbach** [comment]
Hi, yes that makes sense. I added the method in the latest release, let me know if it works for you.

**Comment by LydiaF** [comment]
Thank you v v much :)
