### ISSUE TITLE
Cannot read properties of undefined (reading 'index')

### ISSUE THREAD

**Issue by yaximi111** [lukasbach/react-complex-tree#272]
![image](https://github.com/lukasbach/react-complex-tree/assets/82496137/daa7a318-4116-4803-b99d-1dbe08b3415f)

![image](https://github.com/lukasbach/react-complex-tree/assets/82496137/b1c2e21c-be7f-4bd4-8235-58237fcbcb32)

**Comment by lukasbach** [comment]
I'm not exactly sure why that issue comes up, I suppose it means your data provider returns undefined for certain item IDs. Nevertheless, I suppose the additional check doesn't hurt where you proposed it, I added it in the latest update.

**Comment by yaximi111** [comment]
sorry The data returned by the backend is nested, and there are two pieces of the same data in it, and I expanded them all and one of them became undefined.
Thank you for your reply!

**Comment by yaximi111** [comment]
I've solved the problem with it being data
