### ISSUE TITLE
tree update

### ISSUE THREAD

**Issue by yaximi111** [lukasbach/react-complex-tree#273]
I tried to re-update the whole tree after moving the tree node but did not render it according to the latest data, and after I updated the root node index and assigned the original expandKeys still did not work, how should this problem be solved

**Comment by lukasbach** [comment]
If you change the data behind your tree from outside, you need to tell RCT that data has changed, you can do so by implementing a custom TreeDataProvider. There are some discussions on this in #255 and #244. If this is not your issue, I'd need more details on what you are doing and what is not working.
