### ISSUE TITLE
Missing `activeTreeId` in `TreeEnvironmentRef<T,C>` type

### ISSUE THREAD

**Issue by kamilkazmierczakMtab** [lukasbach/react-complex-tree#277]
**Describe the bug**
`activeTreeId` property is available in environment ref but not available for TS due to missing type in `TreeEnvironmentRef<T,C>`

**To Reproduce**
Assign ref to `UncontrolledTreeEnvironment` and try to use `activeTreeId`

**Expected behavior**
`activeTreeId` is correctly typed

**Comment by lukasbach** [comment]
Hey @kamilkazmierczakMtab, thanks for the report, should be fixed in the new version.
