### ISSUE TITLE
Blueprint renderers don't work with ClickArrowToExpand

### ISSUE THREAD

**Issue by floriancargoet** [lukasbach/react-complex-tree#3]
**Describe the bug**
When using `ClickArrowToExpand` and the blueprint renderers, nothing happens when I click the arrow.

**To Reproduce**
- use the blueprint renderers
- use `ClickArrowToExpand`
- click the arrow to expand
- observe that it doesn't expand

**Expected behavior**
The node should expand when clicking on its arrow.

**Comment by floriancargoet** [comment]
I believe the fix is to add arrowProps to the icon: 
```tsx
  renderItemArrow: (props) => (
    <ChevronRight
      className={classnames(
        Classes.TREE_NODE_CARET,
        props.context.isExpanded
          ? Classes.TREE_NODE_CARET_OPEN
          : Classes.TREE_NODE_CARET_CLOSED
      )}
      // FIX
      {...(props.context.arrowProps as any)}
    />
  ),
```

I casted as  `any` because `ChevronRight` specifies `children: never` in its type whereas `HTMLProps<any>` defines children.

**Comment by lukasbach** [comment]
Fixed, thanks for the implementation suggestion!

**Comment by yashgupta18** [comment]
This might help
https://codesandbox.io/s/1t3bx?file=/src/App.tsx:1330-1374
