### ISSUE TITLE
Custom search

### ISSUE THREAD

**Issue by safadl** [lukasbach/react-complex-tree#304]
Hello,

Is there a way to search the tree from a custom search input? I am aware that there is already a feature to search the tree once we start typing but I want to display the search input at all times.

**Comment by lukasbach** [comment]
You can customize the render logic for the search input, but not that it should always be visible at the moment. But you can use the `expandSubsequently` method on the tree reference to find a specific item and use custom search logic, there is some documentation available here: https://rct.lukasbach.com/docs/guides/search/#finding-items-that-are-not-loaded-in (last section)
