### ISSUE TITLE
Item sort order is not maintained when reparenting multiselections

### ISSUE THREAD

**Issue by tonyketcham** [lukasbach/react-complex-tree#315]
**Describe the bug**
Regression - dragged items (multiple selected) do not maintain their sort order when reparented

**To Reproduce**
Drag a multiple selection of items to a different parent

**Expected behavior**
Should remain same order as initial position

**Screenshots**

https://github.com/lukasbach/react-complex-tree/assets/43280336/163c2dc4-90a8-4c4c-ad3b-fbb382232d7a

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chromium
- Version 120

**Comment by lukasbach** [comment]
I had another look, and I actually believe the item order was never maintained when dropping items, it always used the order in which items where selected when dropping them 🙃 Anyway, I added some additional logic to sort them again in the displayed order when items are dropped in v2.3.3.
