### ISSUE TITLE
Infer `hasChildren` from `children.length`?

### ISSUE THREAD

**Issue by corysimmons** [lukasbach/react-complex-tree#32]
Seems redundant.

**Comment by lukasbach** [comment]
Hi @corysimmons, thanks for the comment!

Actually they are somewhat different, `hasChildren` defines whether an item should behave like one that has children, i.e. be expandable and collapsible. So if you want to have an empty folder that still shows the caret icon and can be expanded or collapsed, it would need to have the prop `hasChildren` set to true, even if the `children` array is empty. If you want empty folders to behave like normal items, they are in fact the same. On hindsight, I admit that this is pretty bad naming, maybe this should be renamed to `hasCaret` or something..

**Comment by corysimmons** [comment]
Ah, that makes a lot of sense, thank you for the examples in your explanation!
