### ISSUE TITLE
Enable setting custom `TreeItemElement` component

### ISSUE THREAD

**Issue by cunj123** [lukasbach/react-complex-tree#333]
**Is your feature request related to a problem? Please describe.**
I am trying to add animation to the item children list when expanding/collapsing. The easiest way to do that would be to put the transition on the height property and toggle the height between some value and 0. 

Currently that is not possible becuase `TreeItemElement` doesn't render anything if the node isn't expanded.

**Describe the solution you'd like**
Allow developers to define a custom `TreeItemElement` where the hide/show behavior can me implemented.

**Describe alternatives you've considered**
Make the default behavior for showing/hiding nodes the one I described, but I don't think that's a good solution.

**Comment by lukasbach** [comment]
Hi, thanks for the suggestion. It's not really feasible to make the entirety of `TreeItemElement` customizable, but I extracted the logic for when it does render its items and when not customizable through the `shouldRenderChildren` prop in v2.3.5. That should hopefully help you achieve what you want.

See [Demo](https://rct.lukasbach.com/storybook/?path=/story/core-basic-examples--animated-expanding-and-collapsing)
and [Demo Implementation](https://github.com/lukasbach/react-complex-tree/blob/main/packages/core/src/stories/BasicExamples.stories.tsx#L561) for details
