### ISSUE TITLE
UncontrolledTreeEnvironment is throwing error

### ISSUE THREAD

**Issue by kherP** [lukasbach/react-complex-tree#355]
**Describe the bug**
it's possible for potentialParent to undefined, causing `potentialParent.children` to throw error.
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'children')

**To Reproduce**
Steps to reproduce the behavior (ideally a codesandbox link or similar if for a library issue):

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. A gif or screencast can also help understand your problem.
<img width="817" alt="image" src="https://github.com/lukasbach/react-complex-tree/assets/12553063/b75f555c-0796-43e6-991d-b4de78193cca">

**Additional context**
You can help by providing additional details that are available to you, such as

- Device if mobile
- Operating System, Browser
- Version of the Library or tool for which you report the bug

**Comment by lukasbach** [comment]
Hello @kherP! Thanks again for your contribution. The change has been released in a new version, please let me know if it solved your problem so I can close this issue if it was resolved.

**Comment by kherP** [comment]
Hi @lukasbach , yes it does. Thank you very much!
