### ISSUE TITLE
no nodes in the tabOrder after drop on non-expanded parent

### ISSUE THREAD

**Issue by marchingband** [lukasbach/react-complex-tree#362]
After executing drag/drop, if the drop recipient is a parent who is not-expanded, then I am unable to use tab to get into the tree.
I am using your library primarily for its accessibility, so I am expecting to find some bugs with the complexity of the key command logic.

**Comment by lukasbach** [comment]
Hi, thanks for the report. The issue should be fixed as of v2.4.3. Please let me know or reopen if something doesn't work as expected.
