### ISSUE TITLE
 TypeError: Cannont read properties of undefined ( reading 'tree-1')

### ISSUE THREAD

**Issue by EasyCanadianGamer** [lukasbach/react-complex-tree#384]
**Describe the bug**
Well when I run the the sample code in my code, the UI is doesn't render.

**To Reproduce**
Steps to reproduce the behavior (ideally a codesandbox link or similar if for a library issue): [CodeSandbox](https://codesandbox.io/p/sandbox/vigorous-tree-j37zyf?file=%2Fsrc%2FApp.jsx%3A9%2C5)

**Expected behavior**
Its gives a white screen showing that the tree is not being displayed
**Screenshots**
If applicable, add screenshots to help explain your problem. A gif or screencast can also help understand your problem.

Also here is the screenshot of the errors I get from the console:
![image](https://github.com/lukasbach/react-complex-tree/assets/39717944/dc495c7b-a6f3-4657-81f1-7a5ba12225e5)

This is without the Error Boundary tags from React:
![image](https://github.com/lukasbach/react-complex-tree/assets/39717944/c2c9b1aa-8f00-48bc-bbf4-388efe94e9a1)

This is with the Error Boundary tags from React ( the something went wrong is where I want to put the tree like a code editor from vscode) : 
![image](https://github.com/lukasbach/react-complex-tree/assets/39717944/a07d9728-b845-4acf-ba2b-2805c598f20c)

**Additional context**
You can help by providing additional details that are available to you, such as

- Windows using the Arc Browser ( uses the chromium engine)

**Comment by lukasbach** [comment]
Hey, thanks for your report. I tried your sandbox link, but it looks like there is something wrong with the JS import, the main JS file doesn't run at all.

That said, can you try adding `viewSate={{ "tree-1": {} }}` as prop to the tree environment to see if that does something?

**Comment by lukasbach** [comment]
Closing this for now, please let me know if the issue persists.
