### ISSUE TITLE
Dragging a unselected node calls canDrag() before selecting it and canDrag receives the seleciton

### ISSUE THREAD

**Issue by floriancargoet** [lukasbach/react-complex-tree#4]
**Describe the bug**
Before calling `canDrag()`, the lib computes `itemsToDrag`.

https://github.com/lukasbach/react-complex-tree/blob/6eb9a0e6baf1c1fcc661fbf0b6681dfae93666c4/packages/core/src/treeItem/useTreeItemRenderContext.ts#L33-L35

When a node is selected and I start dragging another node, the selection is not updated immediately. `canDrag()` receive the selected node instead of the dragged node.

**Comment by lukasbach** [comment]
Should be fixed now, thanks for the heads up.
