### ISSUE TITLE
Do not hide root node and allow multiple root nodes.

### ISSUE THREAD

**Issue by dlech** [lukasbach/react-complex-tree#42]
I'm not sure the current implementation is fully in line with the [the spec](https://www.w3.org/TR/wai-aria-practices-1.1/#tree_roles_states_props) (I realize this is a bit of a gray area).

Currently, a tree like this is generated (only showing `role` attributes):

```html
<div role="tree">
  <ul role="group">
    <li role="treeitem">
      ...
      <ul role="group">
        <li role="treeitem">...</li>
        <li role="treeitem">...</li>
        <li role="treeitem">...</li>
        ...
      </ul>
    </li>
    <li role="treeitem">...</li>
    <li role="treeitem">...</li>
    ...
  </ul>
</div>
```

The spec says:

> - Each element serving as a tree node has role [treeitem](https://www.w3.org/TR/wai-aria-1.1/#treeitem).
> ...
> - Each parent node contains or owns an element with role [group](https://www.w3.org/TR/wai-aria-1.1/#group).

However, the root node lacks the `role` of `"treeitem"`.

Also, the [example implementation](https://files.paciellogroup.com/training/WWW2012/samples/Samples/aria/tree/index.html) also does not have a top-level node with the `role` of `"group"`.

The spec also says:

> Each root node is contained in the element with role tree or referenced by an [aria-owns](https://www.w3.org/TR/wai-aria-1.1/#aria-owns) property set on the tree element.

Which implies that multiple root nodes are expected.

**Comment by dlech** [comment]
It makes sense. It is just a minor annoyance to have to create "another random item" and make TypeScript happy since this item doesn't need to match any schema of the rest of the items.

**Comment by lukasbach** [comment]
Yes, I agree that this is a inconveniance for certain use cases, but imho keeps the API cleaner and code footprint smaller, so I'd rather keep it that way.

**Comment by lukasbach** [comment]
Btw you could also write a custom data provider that wraps your data structure and adds logic to construct a custom root node specifically for your data structure, if you want to keep that root node outside your data tree.
