### ISSUE TITLE
Tree inside form triggers window reload on click

### ISSUE THREAD

**Issue by michaelg9** [lukasbach/react-complex-tree#5]
**Describe the bug**
When the tree is a child of a form element, and the user clicks on any node on the tree, then the window refreshes

**To Reproduce**
Add a tree inside a form element, and click on any node on the tree. The window will refresh

**Expected behavior**
We expect that the primary action will trigger (and maybe expand) but without refreshing the window

**Demo**
https://codesandbox.io/s/react-complex-tree-playground-forked-r69m1?file=/src/App.tsx

**Desktop:**

- OS: iOS
- Browser: Chrome
- Version: Latest, 94

**Root cause**
The container element is a button by default, and the default button type is submit. When a submit button is clicked inside a form it automatically refreshes the window, unless someone calls preventDefault on the form on submit event or the on click event of the button.

**Solution**
Add an attribute type="button" to the button node container:
https://github.com/lukasbach/react-complex-tree/blob/6eb9a0e6baf1c1fcc661fbf0b6681dfae93666c4/packages/core/src/renderers/createDefaultRenderers.tsx#L116

I can raise a PR if needed

Thanks for the great component btw!

**Comment by lukasbach** [comment]
Fixed in 1.1.4
