### ISSUE TITLE
Accessibility in Storybook

### ISSUE THREAD

**Issue by dgreene1** [lukasbach/react-complex-tree#56]
**Describe the bug**

When trying to test the accessibility of the library, you can't focus on the tree and the library does not process key events that it is supposed to, like the down arrow moving lower in the tree at that level.

**To Reproduce**

Try the keyboard shortcuts described in https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-2/treeview-2a.html and you'll find that sometimes the focus shows up and sometimes it doesn't. The most troubling issue is when certain arrow keys accidentally take you out of the tree.

**Expected behavior**

The keyboard behavior described in https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-2/treeview-2a.html should work.

**Screenshots**
n.a.

**Desktop (please complete the following information):**

- Browser: Firefox w/ NVDA
- Version: 98.0.2

**Smartphone (please complete the following information):**

n.a.

**Additional context**

**Comment by lukasbach** [comment]
Ah I found an issue from the last time I worked on some performance upgrades, I'm looking into it. Pretty sure that those issues where introduced after the last release though, this should not happen on any consumable version of the library at the moment.

**Comment by dgreene1** [comment]
@lukasbach I was able to replicate it in the “playground” link on the website so it is occurring out in the published version.

**Comment by dlech** [comment]
> focus leaves the tree and goes somewhere else. I think it goes to rct-livedescription-tree-1

I noticed this too. The default live description contains a link which takes focus even though it is not visible on the screen. 



> Can this rct-livedescription-tree-1 div be removed and made a part of the documentation instead of part of the actual widget?

This can be done in your own app with the `renderLiveDescriptorContainer` prop. But the link should probably be removed or made non-focusable in the default implementation.

**Comment by lukasbach** [comment]
The link in the live descriptor region should not be there anymore, I removed that in https://github.com/lukasbach/react-complex-tree/commit/8a45c1f914f7e4197e0593c9ff30205e0473f51e and deployed afterwards...

Also note that enter does not toggle the collapsed state of an item, it only selects and invokes the primary action, but space does.

**Comment by lukasbach** [comment]
I'll close this for now, please let me know if any other issues persist.
