### ISSUE TITLE
keybinding ovverrides are broken

### ISSUE THREAD

**Issue by dberardo-com** [lukasbach/react-complex-tree#6]
**Describe the bug**
check the doc: https://rct.lukasbach.com/docs/guides/search#configurability

**To Reproduce**
pass this prop to a controlled component: 
 keyboardBindings={{
          renameItem: ["ENTER"],
        }}

![image](https://user-images.githubusercontent.com/65530457/138889712-d4766402-e018-47f8-b39a-aa1b24f8b125.png)

**Comment by lukasbach** [comment]
This is now fixed as of version v1.1.3 of this package. Please update your dependency to receive the fix.

You can now just leave out the unchanged keybindings. There is no breaking change involved, so you don't need to update anything else.

If this issue or a similar problem persists, feel free to reopen this issue or create a new one. Thanks again for your issue report! :)
