### ISSUE TITLE
react-complex-tree and MS Fluent UI Panel

### ISSUE THREAD

**Issue by PooLP** [lukasbach/react-complex-tree#60]
**Describe the bug**
The drop event of react-complex-tree do not work in use with MS Fluent UI Panel

**To Reproduce**
I have created a codeSandBox, if use react-complex-tree directly un page, it work correctly, if use in ms Fluent ui Panel (click open button), the drop functionality do not work (the drag work, but the drop action do not work)

On drop, blue line freeze and onDrop event return nothing

https://codesandbox.io/s/fluentui-panel-and-react-complex-tree-p3e6qq

**Desktop :**

- OS: Windows 11
- Browser : chrome, firefox, edge
- Version : latest

**Comment by lukasbach** [comment]
Hi @PooLP, thanks for the report. Looks like this has the same cause as https://github.com/microsoft/fluentui/issues/12059
FluentUI's panel is capturing drop events. Can you add `layerProps={{ eventBubblingEnabled: true }}` to your panel props?

Example: https://codesandbox.io/s/fluentui-panel-and-react-complex-tree-forked-x4zbwi?file=/src/App.tsx:1910-1953

**Comment by PooLP** [comment]
ho yes, I did not see.
Thanks, i close the issue
