### ISSUE TITLE
ControlledTreeEnvironment and drag & drop

### ISSUE THREAD

**Issue by PooLP** [lukasbach/react-complex-tree#62]
I don't know if it's a bug or a misunderstanding.
Does drag and drop work in ControlledTreeEnvironment  mode?

I have no problem with UncontrolledTreeEnvironment, but after anothers tests with ControlledTreeEnvironment, the Drag&Drop do not work, and I couldn't find the answer in the documentation.

I reroduced the problem in codesandbox :
https://codesandbox.io/s/react-complex-controlledtreeenvironment-drag-ng6mme

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Latest Chrome and Firefox
- Version: latest

Thanks for this excellent lib ;)

**Comment by lukasbach** [comment]
Hi @PooLP! In a controlled tree environment, you will need to handle all state mutations yourself. This means, for drag and drop to work in a controlled environment, you need to implement the [onDrop handler](https://rct.lukasbach.com/docs/api/interfaces/ControlledTreeEnvironmentProps#ondrop) on the environment, and mutate the tree state passed through via `items` yourself. In an uncontrolled environment, this is not necessary as the environment does that for you.

**Comment by PooLP** [comment]
ok, i understand. thanks.
