### ISSUE TITLE
Keyboard navigation is out-of-sync from viewstate

### ISSUE THREAD

**Issue by matthijsgroen** [lukasbach/react-complex-tree#76]
**Describe the bug**

when opening a folder in the tree using the right-arrow, and then move down, the focus is on the item after the tree item, IF the 'items' of the tree are the same. when the items change as well (for instance items keeping track of expand state as well) then it works fine.

**To Reproduce**

1. visit: https://rct.lukasbach.com/docs/guides/controlled-environment/#managing-the-view-state-of-the-tree
2. Click 'Desserts' (it should expand immediately)
3. Press arrow down (focus becomes "Drinks")

**Expected behavior**

1. visit: https://rct.lukasbach.com/docs/guides/controlled-environment/#managing-the-view-state-of-the-tree
2. Click 'Desserts' (it should expand immediately)
3. Press arrow down (focus should become "Cookies")

**Screenshots**

![keyboard-bug](https://user-images.githubusercontent.com/23627/170369747-64832f65-f441-4264-9aef-9aba53f78249.gif)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 102

**Additional context**

I could fix this behaviour in my own application by updating the object reference of `items` whenever the expanded view state changed. I suspect there the keyboard navigation is somehow using an out of date 'linear list' because it only updates when the 'items' change, and not when the 'expandedItems' state changes.

**Comment by matthijsgroen** [comment]
Hmm that Particular issue is fixed, but now a new issue has risen. when I click in the tree and start keyboard navigation I get index errors.

1.1.6
![keyboard-116](https://user-images.githubusercontent.com/23627/170428629-c0bdb0d3-cb5a-4eff-8289-e1783601614c.gif)

with 1.1.7
![keyboard-117](https://user-images.githubusercontent.com/23627/170428660-8a7a6893-db4f-4001-87e2-a43e7d0ba9a9.gif)

**Comment by lukasbach** [comment]
Hm, that is odd, I'm not getting that in any of the storybook instances. Do you have your project deployed anywhere where it would be possible to reproduce this issue?

**Comment by matthijsgroen** [comment]
1. Go to https://geppetto.js.org/app/
2. Check if version commit is `5a005c`. 
3. Press 'Load Demo File'
4. On the top, Press "Composition"
5. In the tree to the left, press "Saturation (2)"
6. Try keyboard navigation

**Comment by lukasbach** [comment]
Thanks, that really was helpful in debugging, I believe I found the issue now. Please try again with RCT version 1.1.8, I hope this time there are no other problems 😅 Let me know if you have any other issues, and btw your project looks awesome! :)

**Comment by matthijsgroen** [comment]
It works perfectly now! Thank you! (will update the online build later)
