### ISSUE TITLE
How to add a new node to the tree?

### ISSUE THREAD

**Issue by arunkumar413** [lukasbach/react-complex-tree#87]
Hello Team,

I just stumbled upon this library. Could you please share more details on how to add,edit, delete nodes and children?

Thanks,
Arun

**Comment by VulumeCode** [comment]
This library is only for rendering a tree, all the default controllers are for managing a static tree. You can use a [Controlled Environment ](https://rct.lukasbach.com/docs/guides/controlled-environment) and manage it yourself. If you keep the tree data (the items prop) in your component state, React will rerender the tree when it changes.

**Comment by lukasbach** [comment]
Yes, thank you @VulumeCode. The other way is to implement a [custom data provider](https://rct.lukasbach.com/docs/guides/custom-data-provider), where you can manually trigger when nodes or their children have changed by managing your own event emitter that handles those events.
